# Generated by Django 5.1.3 on 2024-11-20 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ["-id"]},
        ),
    ]
